# **Домашняя работа №1**

### `Петров Александр ИКБО-40-24`

In [1]:
import numpy as np

In [2]:
# Создаем массив numpy разными способами

arr1 = np.array([8, 10, -3, 0.4])  # просто передаем массив чисел

temp_arr = [0, 4, -1]
arr2 = np.array(temp_arr)  # или можно передать уже созданный список

arr1, arr2

(array([ 8. , 10. , -3. ,  0.4]), array([ 0,  4, -1]))

In [3]:
# numpy также позволяет создавать матрицы

matrix = np.array([[3, 4], [5, 6], [7, 8]])
matrix

array([[3, 4],
       [5, 6],
       [7, 8]])

In [4]:
# А еще можно воспользоваться встроенными функциями

arr3 = np.arange(5)         # перебирает числа от 0 до 5 и создает из них массив
arr4 = np.empty([3, 3])     # создает "пустой" массив; значения внутри - системный мусор
arr5 = np.zeros([2, 1])     # похоже на empty, только каждое значение инициализируется нулем

arr3, arr4, arr5

(array([0, 1, 2, 3, 4]),
 array([[ 1.27189941e-30, -2.54379882e-30,  6.35949704e-31],
        [-2.54379882e-30,  5.53276243e-30, -1.71706420e-30],
        [ 6.35949704e-31, -1.71706420e-30,  9.85722042e-31]]),
 array([[0.],
        [0.]]))

In [5]:
# Посмотрим на форму и тип созданных массивов

print(f"arr1 shape: {arr1.shape} \
        \narr2 shape: {arr2.shape} \
        \nmatrix shape: {matrix.shape}")

print(f"arr1 type: {arr1.dtype} \
        \narr2 type: {arr2.dtype} \
        \nmatrix type: {matrix.dtype}")

arr1 shape: (4,)         
arr2 shape: (3,)         
matrix shape: (3, 2)
arr1 type: float64         
arr2 type: int64         
matrix type: int64


Обратим внимание на то, что arr1 и arr2 имеет одномерную форму, когда как matrix - двумерную

Поработаем над матрицей

In [6]:
# Можно указывать индексы как в двумерном массиве

print(matrix[0][0])  # левый верхний элемент
print(matrix[1][1])  # правый средний элемент

3
6


In [7]:
# А можно через запятую

print(matrix[0, 0])
print(matrix[1, 1])

3
6


In [8]:
# Теперь строки и столбцы

print(matrix[[0, 1], 1])    # берем первую и вторую строку, а значения из второго столбца
print(matrix[:,0])          # берем целиком первый столбец

[4 6]
[3 5 7]


Создадим две тестовых матрицы:

test1:\
(1 2 3 4\
5 6 7 8)

test2:\
(15 16 17 18\
-1 -2 -3 -4)

Обе имеют форму `(2, 4)`. По правилам линейной алгебры, такие массивы можно сложить поэлементно.

In [9]:
test1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
test2 = np.array([[15, 16, 17, 18], [-1, -2, -3, -4]])

print(test1 + test2)

[[16 18 20 22]
 [ 4  4  4  4]]


Все верно! Однако что будет, если попробовать их перемножить? Для умножения матриц необходимо, чтобы число столбцов первой матрицы совпадало с количеством строк второй, что не подходит нашему случаю.

In [10]:
print(test1 * test2)

[[ 15  32  51  72]
 [ -5 -12 -21 -32]]


Вместо ошибки произошло поэлементное умножение.

In [11]:
# numpy предоставляет большое количество встроенных статистических функций

data = np.array([5, 9, -15, 4, 1, 0, 2, 10])

print(np.mean(data))    # среднее значение
print(np.median(data))  # медиана
print(np.var(data))     # дисперсия
print(np.std(data))     # стандартное отклонение

2.0
3.0
52.5
7.245688373094719
